\documentclass{beamer}
%\usetheme{metropolis}
\usepackage[utf8]{inputenc}
\usepackage{polski}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\usepackage{epstopdf}
\usepackage{colortbl, xcolor}
\usepackage{url}

\newcommand\Fontvi{\fontsize{6}{7.2}\selectfont}

\newcommand{\btVFill}{\vskip0pt plus 1filll}

\title{Przewidywanie właściwości sekwencji biologicznych w oparciu o analizę n-gramów}
\date{}
\author{Michał Burdukiewicz}
\institute{Zakład Bioinformatyki i Genomiki, Uniwersytet Wrocławski \\
\begin{flushright}
Promotor pracy: prof. dr hab. Paweł Mackiewicz \\
Promotor pomocniczy: dr Paweł Błażej
\end{flushright}
}

\begin{document}

  <<knitrIntro, echo = FALSE, message=FALSE,warning=FALSE>>=
source("my_ggplot_theme.R")

library(dplyr)
library(reshape2)
library(xtable)
library(biogram)
library(seqinr)
library(VennDiagram)
  
source("script.R")  

print_bt <- function(x) {
  rws <- 0L:(nrow(x) - 1)
  col <- c("\\rowcolor{green!10}", "\\rowcolor{blue!10}", "\\rowcolor{red!10}", "\\rowcolor{yellow!10}")
  print(xtable(x, digits = 0), booktabs = TRUE,
        add.to.row = list(pos = as.list(rws), command = col),
        print.results = FALSE)
}

print_bt2 <- function(x) {
  rws <- seq(1, nrow(x) - 1, by = 2)
  col <- rep("\\rowcolor[gray]{0.85}", length(rws))
  print(xtable(x, digits = 0), booktabs = TRUE,
        add.to.row = list(pos = as.list(rws), command = col),
        print.results = FALSE, include.rownames = FALSE)
}  
  
cls <- c("\\colorbox{green!10}", "\\colorbox{blue!10}", "\\colorbox{red!10}", "\\colorbox{yellow!10}")

group2df <- function(group_list, caption = NULL, label = NULL) {
  tab <- data.frame(Groups = sapply(group_list, function(i)
    paste0(toupper(sort(i)), collapse = ", ")))
  tab <- cbind(ID = 1L:nrow(tab), tab)
  rws <- seq(1, nrow(tab) - 1, by = 2)
  col <- rep("\\rowcolor[gray]{0.85}", length(rws))
  colnames(tab) <- c("Subgroup ID", "Amino acids")
  res <- print(xtable(tab, caption = caption, label = label), 
               include.rownames = FALSE, booktabs = TRUE,
               add.to.row = list(pos = as.list(rws), command = col), print.results = FALSE, 
               caption.placement = "top", sanitize.text.function = identity, 
               sanitize.rownames.function = identity)
  #res
  print(xtable(tab))
}  
  
amyloids_plot <- read.csv("amyloid_plot_data.csv")

levels(amyloids_plot[["et"]]) <- c("Best-performing simplified alphabet", 
                                   "simplified alphabet", "Full alphabet", 
                                   "Standard simplified alphabet")


amyloids_plot[["len_range"]] <- factor(amyloids_plot[["len_range"]], 
                                       levels = c("Test peptide length: 6 ", "Test peptide length: 7-10", 
                                                  "Test peptide length: 11-15", "Test peptide length: 16-25"))

subdat <- filter(amyloids_plot, pos == "Training peptide length: 6")

best_enc <- list(c("G"), 
                 c("K", "P", "R"),
                 c("I", "L", "V"),
                 c("F", "W", "Y"),
                 c("A", "C", "H", "M"),
                 c("D", "E", "N", "Q", "S", "T"))
names(best_enc) <- 1L:6


@
  

\maketitle

\begin{frame}{Plan prezentacji}

\tableofcontents

\end{frame} 

\begin{frame}{} 

Badania \textit{in silico} pozwalają efektywniej planować prace eksperymentalne.

Przykłady: 

\begin{itemize}
\item przewidywanie właściwości białek (np. obecność sekwencji sygnałowych, amyloidogenność),  
\item przewidywanie warunków hodowlanych mikroorganizmów.
\end{itemize}

\end{frame}   
  
\begin{frame}{Cel} 

Opracowanie metodologii analizy sekwencji biologicznych opierającej się na zrozumiałych dla człowieka regułach decyzyjnych. 

\end{frame}   

\section{n-gramy i uproszczone alfabety}

\begin{frame}
n-gramy (k-tuple, k-mery):
\begin{itemize}
\item podsekwencje (ciągłe lub z przerwami) $n$ reszt aminokwasowych lub nukleotydowych,
\item bardziej informatywne niż pojedyncze reszty.
\end{itemize}
\end{frame}  

\begin{frame}

<<echo = FALSE, message=FALSE,warning=FALSE>>=

seq1 <- c("f", "k", "v", "w", "p", "d", "h", "g", "s", "g")
seq2 <- c("y", "m", "c", "i", "y", "r", "a", "q", "t", "n")

sample_seq <- matrix(toupper(c(seq1, seq2)), ncol = 10, byrow = TRUE)

generate_ngrams <- function(x) 
  decode_ngrams(x) %>% 
  gsub("_", "-", x = .) %>% 
  paste0(paste0('\\textcolor{',  colors, '}{\\texttt{'), .) %>% 
  paste0(., "}}") %>% 
  .[1L:4] %>% 
  paste0(collapse = ", ") 

colors <- c("red", "blue")

przyklady <- list(seq2ngrams(sample_seq, 1, aa_v, d = 0), 
                  seq2ngrams(sample_seq, 2, aa_v, d = 0), 
                  seq2ngrams(sample_seq, 2, aa_v, d = 1), 
                  seq2ngrams(sample_seq, 3, aa_v, d = c(2, 0)))

colored_ngrams <- lapply(przyklady, generate_ngrams) 


@

Peptyd I: \textcolor{red}{\texttt{\Sexpr{toupper(paste0(seq1, collapse = ""))}}}

Peptyd II: \textcolor{blue}{\texttt{\Sexpr{toupper(paste0(seq2, collapse = ""))}}}

\medskip

Przykłady n-gramów uzyskanych z peptydów I i II:

\begin{enumerate}
    \item 1-gramy: \Sexpr{colored_ngrams[[1]]},
    \item 2-gramy: \Sexpr{colored_ngrams[[2]]},
    \item 2-gramy (nieciągłe): \Sexpr{colored_ngrams[[3]]},
    \item 3-gramy (nieciągłe): \Sexpr{colored_ngrams[[4]]}.
\end{enumerate}

\end{frame}



\begin{frame}
<<echo = FALSE, message=FALSE,warning=FALSE,fig.height=4.5,results='asis'>>=
L <- 1
m <- 20 
m2 <- 6
n <- 1:5
n_max <- L*m^n
n_max2 <- L*m2^n
#dat <- data.frame(n = c(n, n), n_max = c(n_max, n_max2), m = c(rep(m, 5), rep(m2, 5)))
dat <- data.frame(n = n, n_max = n_max, m = rep(m, 5))
dat[["m"]] <- factor(dat[["m"]])

ggplot(dat, aes(x = n, y = n_max, color = m, label = formatC(n_max, digits = 4))) + 
  geom_line(linetype="dotted", size=1.5) + 
  geom_point(size=4, shape=16) +
  geom_text(size = 4, vjust = -1.5, hjust = "inward", color = "red") +
  coord_cartesian(ylim = c(1, 4.5e7)) +
  scale_x_continuous("Długość ciągłego n-gramu (n)", breaks = 0L:5) +
  scale_y_continuous("Liczba potencjalnych n-gramów (skala logarytmiczna)",
                     trans = "log10") +
  scale_color_discrete("Rozmiar alfabetu") +
  my_theme
@

Dłuższe n-gramy są bardziej informatywne, ale tworzą większe przestrzenie atrybutów, które są trudniejsze do analizy.

\end{frame}

\begin{frame}{QuiPT}  

<<echo = FALSE, message=FALSE,warning=FALSE,fig.height=3.6,results='asis'>>=
load("data/times2.RData")

times_dat <- do.call(rbind, lapply(times, function(i) 
  t(sapply(i, function(j) {
    c(slow = unname(j[["slow"]]["elapsed"]),
      quick = unname(j[["quick"]]["elapsed"]))
  }))
)) %>% 
  data.frame %>% 
  mutate(size = sort(rep(1L:5*10, 10))) %>% 
  melt(id.vars = "size") %>% 
  group_by(size, variable) %>% 
  summarise(value = mean(value)) %>% 
  ungroup %>% 
  mutate(variable = factor(variable, labels = c("Test permutacyjny", "QuiPT")))

ggplot(times_dat, aes(x = size, y = value, color = variable)) +
  geom_point() +
  geom_line(linetype = "dotted") +
  scale_y_continuous("Czas [s]") +
  scale_x_continuous("Liczba testowanych n-gramów") +
  scale_color_manual("Test", values = c("red", "blue")) +
  my_theme
@

QuiPT (dostępny jako funkcja w pakiecie \textbf{biogram}) jest szybszy niż klasyczne testy permutacyjne.
\end{frame}

\begin{frame}{Uproszczone alfabety}
Uproszczone alfabety:
\begin{itemize}
\item aminokwasy są grupowane w większe zbiory na podstawie 
określonych kryteriów,
\item łatwiejsze przewidywanie struktur~\citep{murphy_simplified_2000},
\item tworzenie bardziej uogólnionych modeli.
\end{itemize}
\end{frame}


\begin{frame}{Uproszczone alfabety}
Poniższe peptydy wydają się być całkowicie różne pod względem składu aminokwasowego.

Peptyd I: 

\texttt{\Sexpr{toupper(paste0(seq1, collapse = ""))}}

\medskip

Peptyd II: 

\texttt{\Sexpr{toupper(paste0(seq2, collapse = ""))}}

\end{frame}  


\begin{frame}
<<echo = FALSE, message=FALSE,warning=FALSE,fig.height=4.5,results='asis'>>=
seq_dat <- rbind(data.frame(seq = "Sekwencja I", pos = 1L:10, 
                            aa = seq1, val = aaprop["ARGP820101", seq1]),
                 data.frame(seq = "Sekwencja II", pos = 1L:10, 
                            aa = seq2, val = aaprop["ARGP820101", seq2])) %>% 
  mutate(hydroph = val < 0.4)

ggplot(seq_dat, aes(x = factor(pos), y = val, label = toupper(aa), 
                    group = seq, colour = hydroph)) +
  geom_text(vjust = "outward", size = 4.5, show_guide = FALSE, fontface = "bold") +
  #geom_point(size = 0) +
  geom_line(linetype = "dotted", color = "black") +
  facet_wrap(~ seq, ncol = 1) +
  scale_x_discrete("Pozycja") +
  scale_y_continuous("Hydrofobowość (Argos et al., 1982)", expand = c(.1, .1)) +
  scale_color_manual(values = c("green", "orange")) +
  #guides(colour = guide_legend(override.aes = list(size=4))) +
  my_theme 
@

\end{frame}  

\begin{frame}
\begin{table}
\begin{tabular}{cl}
\toprule
Grupa & Aminokwasy \\ 
\midrule
 \textcolor{green}{1} & \textcolor{green}{C, I, L, K, M, F, P, W, Y, V} \\ 
 \textcolor{orange}{2} & \textcolor{orange}{A, D, E, G, H, N, Q, R, S, T} \\ 
\bottomrule
\end{tabular}
\end{table}

\begin{columns}
\begin{column}{0.15\textwidth}
 
Peptyd I: 

Peptyd II: 

\end{column}
\begin{column}{0.1\textwidth}

\texttt{\textcolor{green}{\Sexpr{toupper(paste0(seq1[1L:5], collapse = ""))}}}\texttt{\textcolor{orange}{\Sexpr{toupper(paste0(seq1[6L:10], collapse = ""))}}} 

\texttt{\textcolor{green}{\Sexpr{toupper(paste0(seq2[1L:5], collapse = ""))}}}\texttt{\textcolor{orange}{\Sexpr{toupper(paste0(seq2[6L:10], collapse = ""))}}} 

\end{column}
\begin{column}{0.02\textwidth}  %%<--- here

\textrightarrow

\textrightarrow
\end{column}
\begin{column}{0.1\textwidth}  %%<--- here

\texttt{\textcolor{green}{\Sexpr{toupper(paste0(rep(1, 5), collapse = ""))}}}\texttt{\textcolor{orange}{\Sexpr{toupper(paste0(rep(2, 5), collapse = ""))}}}

\texttt{\textcolor{green}{\Sexpr{toupper(paste0(rep(1, 5), collapse = ""))}}}\texttt{\textcolor{orange}{\Sexpr{toupper(paste0(rep(2, 5), collapse = ""))}}}
\end{column}
\end{columns}
\end{frame}  



\section{Przewidywanie amyloidów}

\begin{frame}{Białka amyloidowe}

Agregaty białek amyloidowe występują w tkankach osób cierpiących na zaburzenia 
neurodegeneracyjne, takie jak choroba Alzheimera i Parkinsona, a także wiele innych 
schorzeń.

\begin{figure} 
\includegraphics[width=0.61\textwidth]{static_figure/amyloid_aggregates.jpg}
\end{figure}

\footnotesize
Agregaty amyloidowe (czerwone) wokół neuronów (zielone). Strittmatter Laboratory, Yale University.

\end{frame}  

  
\begin{frame}{Białka amyloidowe}

Za agregację białek amyloidogennych odpowiedzialne są sekwencje peptydowe o właściwościach amyloidogennych (hot spots):

\begin{itemize}
\item krótkie (6-15 aminokwasów),
\item bardzo zmienny, zazwyczaj hydrofobowy skład aminokwasowy,
\item tworzą unikalne $\beta$-struktury.
\end{itemize}

\begin{figure} 
\includegraphics[width=0.9\textwidth]{static_figure/zipper_structure.jpg}
\end{figure}

\footnotesize\citet{sawaya_atomic_2007}
\end{frame}


\begin{frame}{AmyloGram}
AmyloGram: oparte na analizie n-gramowej narzędzie do przewidywania amyloidów~\citep{burdukiewicz_prediction_2016, BurdukiewiczAmyloidogenicmotifsrevealed2017a}.
\end{frame}


\begin{frame}

\vspace{2cm}

\begin{figure} 
\includegraphics[width=0.95\textwidth]{static_figure/ngram1.eps}
\end{figure}

\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}

  \end{frame}

\begin{frame}{Walidacja krzyżowa}
  <<echo = FALSE, message=FALSE,warning=FALSE,fig.align='center',fig.height=4>>=

levels(subdat[["len_range"]]) <- c("Zbiór testowy (peptydy o długości 6)", 
                                   "Zbiór testowy (peptydy o długości 7-10)", 
                                   "Zbiór testowy (peptydy o długości 11-15)", 
                                   "Zbiór testowy (peptydy o długości 16-25)")

levels(subdat[["et"]]) <-  c("Najlepszy uproszczony alfabet", "Uproszczony alfabet", 
                             "Pełny alfabet", "Standardowy uproszczony alfabet")

ggplot(subdat, aes(x = len_range, y = AUC_mean)) +
  geom_boxplot(outlier.color = NA, outlier.shape = 16, outlier.size = 3, color = NA, fill = NA) +
  geom_point(data = filter(subdat, et == "Pełny alfabet"), 
             aes(x = len_range, y = AUC_mean, color = et, shape = et), size = 3) +
  scale_x_discrete("") +
  scale_y_continuous("Średnie AUC") +
  scale_shape_manual("", values = c(16, 16, 15, 15)[3], drop = TRUE) +
  scale_color_manual("", values = c("red", "grey", "green", "blue")[3], drop = TRUE) +
  guides(color = guide_legend(nrow = 2), shape = guide_legend(nrow = 2)) + 
  #facet_wrap(~ pos, nrow = 3) +
  ggtitle("Zbiór treningowy (peptydy o długości 6)") + 
  my_theme + 
  coord_flip()

@
%AUC (Area Under the Curve) measures the performance of a classifier (1 - classifier always properly recognizes amyloid proteins, 0 - classifier never properly recognizes amyloid proteins).

\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}

\end{frame}



\begin{frame}{Standardowe uproszczone alfabety}
Opublikowano kilka uproszczonych alfabetów, które w założeniu miały służyć do opisywania struktur drugo- i trzeciorzędowych białek~\citep{kosiol_new_2004, melo_accuracy_2006}.
  \end{frame}
  
    \begin{frame}{Standardowe uproszczone alfabety}
\vspace{2cm}
\begin{figure} 
\includegraphics[width=0.95\textwidth]{static_figure/ngram2.eps}
\end{figure}

\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}

  \end{frame}


    \begin{frame}{Walidacja krzyżowa}
  <<echo = FALSE, message=FALSE,warning=FALSE,fig.align='center',fig.height=4>>=
ggplot(subdat, aes(x = len_range, y = AUC_mean)) +
  geom_boxplot(outlier.color = NA, outlier.shape = 16, outlier.size = 3, color = NA, fill = NA) +
  geom_point(data = filter(subdat, et %in% c("Pełny alfabet", "Standardowy uproszczony alfabet")), 
             aes(x = len_range, y = AUC_mean, color = et, shape = et), size = 3) +
  scale_x_discrete("") +
  scale_y_continuous("Średnie AUC") +
  scale_shape_manual("", values = c(16, 16, 15, 15)[3L:4], drop = TRUE) +
  scale_color_manual("", values = c("red", "grey", "green", "blue")[3L:4], drop = TRUE) +
  guides(color = guide_legend(nrow = 2), shape = guide_legend(nrow = 2)) + 
  #facet_wrap(~ pos, nrow = 3) +
  ggtitle("Zbiór treningowy (peptydy o długości 6)") + 
  my_theme + 
  coord_flip()

@

Standardowe alfabety aminokwasowe nie poprawiają jakości predykcji amyloidów.
  
\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}  
  \end{frame}


\begin{frame}{Nowe uproszczone alfabety}

\begin{itemize}
\item 17 miar fizykochemicznych wybranych z bazy AAIndex: 
  \begin{itemize}
    \item rozmiar, 
    \item hydrofobowość, 
    \item częstość w $\beta$-kartkach,
    \item zdolność do tworzenia kontaktów.
  \end{itemize}
  \item 524 284 uproszczonych alfabetów aminokwasowych o różnej wielkości (od 3 do 6 grup).
  \end{itemize}

\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
    \end{frame}
  
    \begin{frame}{Nowe uproszczone alfabety}
\begin{figure} 
\includegraphics[width=0.95\textwidth]{static_figure/ngram3.eps}
\end{figure}

\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
  \end{frame}



\begin{frame}{Walidacja krzyżowa}
  <<echo = FALSE, message=FALSE,warning=FALSE,fig.align='center',fig.height=4>>=
subdat2 <- droplevels(filter(subdat, et != "Najlepszy uproszczony alfabet"))

ggplot(subdat2, aes(x = len_range, y = AUC_mean)) +
  geom_boxplot(outlier.color = "grey", outlier.shape = 16, outlier.size = 3, color = "black", fill = "white") +
  geom_point(data = filter(subdat2, et %in% c("Pełny alfabet", "Standardowy uproszczony alfabet")), 
             aes(x = len_range, y = AUC_mean, color = et, shape = et), size = 3) +
  scale_x_discrete("") +
  scale_y_continuous("Średnie AUC") +
  scale_shape_manual("", values = c(16, 16, 15, 15)[2L:4], drop = FALSE) +
  scale_color_manual("", values = c("red", "grey", "green", "blue")[2L:4], drop = FALSE) +
  guides(color = guide_legend(nrow = 2), shape = guide_legend(nrow = 2)) + 
  #facet_wrap(~ pos, nrow = 3) +
  ggtitle("Zbiór treningowy (peptydy o długości 6)") + 
  my_theme + 
  coord_flip()

@
%  \small
%Hinges of boxes correspond to 
%the 0.25 and 0.75 quartiles. The bar inside the box represents the median. The 
%gray circles correspond to the simplified alphabets with the AUC outside the 0.95 
%confidence interval.
\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
  
\end{frame}


  
\begin{frame}{Najlepszy uproszczony alfabet}
  <<echo = FALSE, message=FALSE,warning=FALSE,fig.align='center',fig.height=4>>=

ggplot(subdat, aes(x = len_range, y = AUC_mean)) +
  geom_boxplot(outlier.color = "grey", outlier.shape = 16, outlier.size = 3) +
  geom_point(data = filter(subdat, et != "Uproszczony alfabet"), 
             aes(x = len_range, y = AUC_mean, color = et, shape = et), size = 3) +
  scale_x_discrete("") +
  scale_y_continuous("Średnie AUC") +
  scale_shape_manual("", values = c(16, 16, 15, 15), drop = FALSE) +
  scale_color_manual("", values = c("red", "grey", "green", "blue"), drop = FALSE) +
  guides(color = guide_legend(nrow = 2), shape = guide_legend(nrow = 2)) + 
  #facet_wrap(~ pos, nrow = 3) +
  ggtitle("Zbiór treningowy (peptydy o długości 6)") + 
  my_theme + 
  coord_flip()
@
\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
\end{frame}

\begin{frame}{Najlepszy uproszczony alfabet}
<<echo = FALSE, message=FALSE,warning=FALSE,fig.align='center',fig.height=4>>=
# cat(group2df(best_enc, caption = "The best-performing simplified alphabet."))
@
   \begin{table}[ht]
\centering
\begin{tabular}{rl}
  \toprule
Grupa & Aminokwasy \\ 
  \midrule
  1 & G \\ 
   \rowcolor[gray]{0.85}  2 & K, P, R \\ 
    3 & I, L, V \\ 
   \rowcolor[gray]{0.85}  4 & F, W, Y \\ 
    5 & A, C, H, M \\ 
   \rowcolor[gray]{0.85}  6 & D, E, N, Q, S, T \\ 
   \bottomrule
\end{tabular}
\end{table}
   \btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
   \end{frame}

     \begin{frame}{Najlepszy uproszczony alfabet}
   \begin{table}[ht]
\centering
\begin{tabular}{rl}
  \toprule
Grupa & Aminokwasy \\ 
  \midrule
  1 & G \\ 
   \rowcolor[gray]{0.85}  2 & K, P, R \\ 
   \rowcolor{blue!20} 3 & I, L, V \\ 
   \rowcolor{blue!20}  4 & F, W, Y \\ 
    5 & A, C, H, M \\ 
   \rowcolor[gray]{0.85}  6 & D, E, N, Q, S, T \\ 
   \bottomrule
\end{tabular}
\end{table}
   
Grupy 3 i 4 - aminokwasy hydrofobowe.  
\btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
   \end{frame}
  
  
     \begin{frame}{Najlepszy uproszczony alfabet}
   \begin{table}[ht]
\centering
\begin{tabular}{rl}
  \toprule
Grupa & Aminokwasy \\ 
  \midrule
  1 & G \\ 
   \rowcolor{red!20}  2 & K, P, R \\ 
    3 & I, L, V \\ 
   \rowcolor[gray]{0.85}  4 & F, W, Y \\ 
    5 & A, C, H, M \\ 
   \rowcolor[gray]{0.85}  6 & D, E, N, Q, S, T \\ 
   \bottomrule
\end{tabular}
\end{table}
   
Grupa 2 - reszty aminokwasowe zakłócające $\beta$-struktury.  
   \btVFill

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
   \end{frame}  
   

\begin{frame}{}
Czy informatywne n-gramy znalezione przez QuiPT są związane z amyloidogennością?
\end{frame}


\begin{frame}{Informatywne n-gramy}
<<echo = FALSE,message=FALSE,fig.align='center',fig.width=11.5,warning=FALSE>>=
ngram_freq <- read.csv("ngram_freq.csv")

ngram_freq_plot <- mutate(ngram_freq, decoded_name = gsub("_", "-", decoded_name)) %>%
  mutate(decoded_name = factor(decoded_name, levels = as.character(decoded_name)),
         amyloid = diff_freq > 0) %>%
  melt() %>%
  filter(variable %in% c("pos", "neg"),
         association != "Not found") %>%
  droplevels %>%
  mutate(variable = factor(variable, labels = c("Amyloid", "Nieamyloid")),
         association = factor(association, levels = c("Amyloidogenny", "Nieamyloidogenny")))

ggplot(ngram_freq_plot, aes(x = decoded_name, y = value)) +
  geom_bar(aes(fill = variable), position = "dodge", stat = "identity") +
  geom_point(data = group_by(ngram_freq_plot, decoded_name)  %>% filter(value == max(value)),
             aes(y = value + 0.004, shape = association), size = 6) +
  scale_fill_manual("", values = c("gold", "darkmagenta")) +
  scale_shape_manual("Motyw:", breaks = c("Amyloidogenny", "Nieamyloidogenny"), values = c(16, 17, NA)) +
  scale_y_continuous("Częstość") +
  scale_x_discrete("") +
  theme_bw(base_size = 18) +
  theme(panel.grid.major.y = element_line(color = "lightgrey", size = 0.5),
        legend.position = "bottom") 

@

Spośród 65 najbardziej informatywnych n-gramów, 15 (23\%) jest również obecnych w motywach aminokwasowych znalezionych ekperymentalnie~\citep{paz_sequence_2004}.

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
\end{frame}


\begin{frame}{Porównanie z innymi narzędziami}

\begin{table}[ht]
\centering

\begin{tabular}{ccccc}
  \toprule
Program & AUC & MCC \\ 
  \midrule
AmyloGram & \textbf{0.8972} & \textbf{0.6307} \\ 
  \rowcolor{white}PASTA 2.0 \citep{walsh_pasta_2014} & 0.8550 & 0.4291  \\ 
   FoldAmyloid \citep{garbuzynskiy_foldamyloid:_2010} & 0.7351 & 0.4526  \\ 
  \rowcolor{white}APPNN \citep{familia_prediction_2015} & 0.8343 & 0.5823  \\ 
   \bottomrule
\end{tabular}
\end{table}

Klasyfikator wytrenowany z wykorzystaniem najlepszego uproszczonego alfabetu, AmyloGram, został porównany z innymi narzędziami do przewidywania amyloidów z użyciem zewnętrznego zbioru danych \textit{pep424}.
\btVFill
\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}


\end{frame}

% \begin{frame}{Benchmark results}
% 
% \begin{table}[ht]
% \centering
% 
% \begin{tabular}{ccccc}
%   \toprule
% Classifier & AUC & MCC \\ 
%   \midrule
% AmyloGram & \textbf{0.8972} & \textbf{0.6307} \\ 
%   \rowcolor{white}PASTA 2.0 \citep{walsh_pasta_2014} & 0.8550 & 0.4291  \\ 
%    FoldAmyloid \citep{garbuzynskiy_foldamyloid:_2010} & 0.7351 & 0.4526  \\ 
%   \rowcolor{white}APPNN \citep{familia_prediction_2015} & 0.8343 & 0.5823  \\ 
%    \bottomrule
% \end{tabular}
% \end{table}
% 
% MCC (Matthew's Correlation Coefficient) measures the performance of a classifier (1 - classifier always properly recognizes amyloid proteins, -1 - classifier never properly recognizes amyloid proteins).
% 
% \end{frame}



\begin{frame}{Walidacja eksperymentalna}
\begin{figure} 
\includegraphics[width=0.95\textwidth]{static_figure/FalsePositives.eps}
\end{figure}
\end{frame}

\begin{frame}{Walidacja eksperymentalna}
\begin{figure} 
\includegraphics[width=0.95\textwidth]{static_figure/ExperimentalValidation.eps}
\end{figure}
\end{frame}

\begin{frame}{Nowe białko amyloidowe}

\includegraphics[width=0.75\textwidth]{static_figure/line.jpg}

Nowy amyloid funkcjonalny produkowany przez Methanospirillum sp. \citep{10.3389/fmicb.2018.02729} został wybrany do analiz \textit{in vitro} dzięki wskazaniom AmyloGramu.

\end{frame}

\section{Przewidywanie peptydów sygnałowych}

\begin{frame}{Peptydy sygnałowe}

\begin{figure} 
\includegraphics[width=0.75\textwidth]{static_figure/SP.eps}
\end{figure}

Peptydy sygnałowe:
        \begin{itemize}[<+->]
          \item krótkie (20-30 reszt) N-końcowe fragmenty białek tworzące $\alpha$-helisy,
            \item kierują białka do układu wewnątrzbłonowego a następne do sekrecji lub kompartymentów wewnątrzkomórkowch.
        \end{itemize}
\end{frame}


  
\begin{frame}{Peptydy sygnałowe}

\begin{figure} 
\includegraphics[width=0.75\textwidth]{static_figure/SP.eps}
\end{figure}

Peptydy sygnałowe są bardzo zmienne, ale zawsze zawierają trzy charakterystyczne domeny~\citep{hegde_surprising_2006}:
\begin{itemize}
        \item n-region: 5-8 dodatnio naładowanych reszt aminokwasowych~\citep{nielsen_prediction_1998},
        \item h-region: bardzo hydrofobowe reszty~\citep{nielsen_prediction_1998},
        \item c-region: kilka (3-5) polarnych reszt.
\end{itemize}

\end{frame}


%Peptydy sygnałowe rozpoczynają się naładowanym dodatnio n-regionem, po którym występuje hydrofobowy h-region i c-region zakończony miejscem cięcia rozpoznawanym przez peptydazę sygnałową. 

  
\begin{frame}{Peptydy sygnałowe}  
Skład aminokwasowy peptydów sygnałowych u \textit{Plasmodium} sp. (do których należy m. in. zarodziec malarii) jest inny od składu peptydów sygnałowych innych eukariontów. Dlatego też narzędzia do przewidywania peptydów sygnałowych źle radzą sobie z przewidywaniem peptydów sygnałowych u \textit{Plasmodium} sp.

<<echo = FALSE, message=FALSE,warning=FALSE,fig.height=4,results='asis'>>=
plot_pca(pca_full)
  #ggtitle("PCA częstości aminokwasów w peptydach sygnałowych")
@  

PCA częstości aminokwasów.
\end{frame}  

\begin{frame}{signalHsmm}

signalHsmm \citep{BurdukiewiczPredictionSignalPeptides2018}: zastosowanie ukrytych modeli semi-Markowa i uproszczonych alfabetów aminokwasowych w celu przewidywania peptydów sygnałowych w białkach \textit{Plasmodium} sp.

\begin{figure} 
\includegraphics[width=0.75\textwidth]{static_figure/HSMMs.eps}
\end{figure}

\end{frame}

\begin{frame}{Porównanie z innymi predyktorami}
signalHsmm efektywnie uczy się rozpoznawać peptydy sygnałowe na bardzo małych zbiorach danych.

Przewidywania signalHsmm są na tyle uniersalne, że pozwalają również przewiywać nietypowe peptydy sygnałowe spotykane w białkach \textit{Plasmodium} sp.

W celu porównania się z innymi klasyfikatorami, powstały dwie iteracje signalHsmm: signalHsmm-2010, oparty na peptydach sygnałowych użytych do uczenia signalP 4.1~citep{petersen_signalp_2011} oraz signalHsmm-1987, oparty na danych dostępnych w 1987, kiedy opublikowano pierwsze narzędzie do przewidywania peptydów sygnałowych.

\btVFill

\tiny Burdukiewicz, M., Sobczyk, P., Chilimoniuk, J., Gagat, P., and Mackiewicz, P. (2018). Prediction of Signal Peptides in Proteins from Malaria Parasites. International Journal of Molecular Sciences 19, 3709.

\end{frame}

\begin{frame}{Porównanie z innymi predyktorami}

\begin{table}[H]
\centering
\small
\begin{tabular}{rllll}
  \toprule
Algorytm & Czułość & Swoistość & MCC & AUC \\ 
  \midrule
signalP 4.1 (no tm) & 0.8235 & 
0.9100 & 0.6872 & 
0.8667 \\ 
   \rowcolor[gray]{0.85}signalP 4.1 (tm) 
& 0.6471 & 
0.9431 & 0.6196 & 0.7951 \\ 
  signalP 3.0 (NN) & 0.8824 
& 0.9052 & 0.7220 & 
0.8938 \\ 
   \rowcolor[gray]{0.85}signalP 3.0 (HMM) 
 & 0.6275 & 
0.9194 & 0.5553 & 0.7734 \\ 
  PrediSi & 0.3333 & \textbf{0.9573} 
& 0.3849 & 0.6453 
\\ 
   \rowcolor[gray]{0.85}Philius 
& 0.6078 & 
0.9336 & 0.5684 & 0.7707 \\ 
  Phobius & 0.6471 & 0.9289 & 
0.5895 & 0.7880 \\ 
   \rowcolor[gray]{0.85}signalHsmm-2010 & 0.9804 & 0.8720 & 0.7409 & 0.9262 \\ 
  signalHsmm-2010 (ident. 50\%) & \textbf{1.0000} & 0.8768 & \textbf{0.7621} & 
\textbf{0.9384} \\ 
   \rowcolor[gray]{0.85}signalHsmm-2010 (pełny alfabet) & 0.8431 & 0.9005 & 0.6853 & 
0.8718 \\ 
  signalHsmm-1987 & 0.9216 & 0.8910 & 0.7271 & 0.9063 \\ 
   \rowcolor[gray]{0.85}signalHsmm-1987 (ident. 50\%) & 0.9412 & 0.8768 & 0.7194 
& 
0.9090 \\ 
  signalHsmm-1987 (pełny alfabet) & 0.7647 & 0.9052 & 0.6350 & 0.8350 \\ 
   \bottomrule
\end{tabular}
\end{table}

\tiny Burdukiewicz, M., Sobczyk, P., Chilimoniuk, J., Gagat, P., and Mackiewicz, P. (2018). Prediction of Signal Peptides in Proteins from Malaria Parasites. International Journal of Molecular Sciences 19, 3709.


\end{frame}


\section{Przewidywanie warunków hodowlanych metanogenów}

\begin{frame}{Methanogram: narzędzie predykcyjne bazy PhyMet\textsuperscript{2} (phymet2.biotech.uni.wroc.pl)}
\begin{figure} 
\includegraphics[width=0.45\textwidth]{static_figure/suplem2.eps}
\end{figure}


\tiny{Burdukiewicz, M., Gagat, P., Jabłoński, S., Chilimoniuk, J., Gaworski, M., Mackiewicz, P., and Łukaszewicz, M. (2018). PhyMet2: a database and toolkit for phylogenetic and metabolic analyses of methanogens. Environmental Microbiology Reports 10, 378–382.}

\end{frame}

\begin{frame}
\begin{figure} 
\includegraphics[width=0.85\textwidth]{static_figure/Figure2.eps}
\end{figure}

\tiny{Burdukiewicz, M., Gagat, P., Jabłoński, S., Chilimoniuk, J., Gaworski, M., Mackiewicz, P., and Łukaszewicz, M. (2018). PhyMet2: a database and toolkit for phylogenetic and metabolic analyses of methanogens. Environmental Microbiology Reports 10, 378–382.}


\end{frame}

\begin{frame}{Podsumowanie}
\small\begin{itemize}
\item Zastosowanie n-gramów (k-merów), czyli ciągów aminokwasów lub nukleotydów o długości $n$ okazało się skuteczne do charakterystyki sekwencji peptydów sygnałowych i amyloidogennych oraz markerów molekularnych metanogenów, a następnie do przewidywania tych peptydów oraz optymalnych warunków hodowli metanogenów w oparciu o te markery.
\item Zastosowanie uproszczonych alfabetów aminokwasowych, w których aminokwasy są grupowane ze względu na swoje podobieństwo fizykochemiczne lub funkcjonalne, okazało się bardzo dobrym podejściem do opisu sekwencji aminokwasowych o zróżnicowanym składzie i wyeksponowania ich cech istotnych do przewidywania peptydów sygnałowych i amyloidogennych.
\item Opracowana procedura QuiPT (\textbf{Qui}ck \textbf{P}ermutation \textbf{T}est) pozwala na szybki wybór najbardziej informatywnych n-gramów i uzyskiwanie dokładnych p-wartości.
\item Zastosowana metodologia tworzenia uproszczonych alfabetów umożliwia identyfikowania kluczowych cech związanych z charakterystycznymi cechami peptydów.
\end{itemize}
\end{frame}

\begin{frame}{Podsumowanie}

Web serwery:
\begin{itemize}
\item \textbf{AmyloGram}: \url{http://www.smorfland.uni.wroc.pl/shiny/AmyloGram/}.
\item \textbf{MethanoGram}: \url{http://www.smorfland.uni.wroc.pl/shiny/MethanoGram/}.
\item \textbf{signalHsmm}: \url{http://www.smorfland.uni.wroc.pl/shiny/signalHsmm/}.
\end{itemize}


Pakiety \textbf{R}:
\begin{itemize}
\item \textbf{biogram}: \url{https://cran.r-project.org/package=biogram}.
\item \textbf{AmyloGram}: \url{https://cran.r-project.org/package=AmyloGram}.
\item \textbf{signalHsmm}: \url{https://cran.r-project.org/package=signalHsmm}.
\end{itemize}
\end{frame}  

\begin{frame}{Podsumowanie}
\begin{figure} 
\includegraphics[width=0.75\textwidth]{static_figure/r1.png}
\includegraphics[width=0.75\textwidth]{static_figure/r2.png}
\end{figure}
\end{frame}


\begin{frame}{Podziękowania}
Mentorzy:
\begin{itemize}
\item \textbf{Paweł Mackiewicz (Uniwersytet Wrocławski)}.
\item Małgorzata Kotulska (Politechnika Wrocławska).
\item Marcin Łukaszewicz (Uniwersytet Wrocławski).
\item Andrzej Dąbrowski (Uniwersytet Wrocławski).
\item Stefan Rödiger (Brandenburg University of Technology Cottbus-Senftenberg).
\item Henrik Nielsen (Technical University of Denmark).
\item Lars Kaderali (University of Greifswald).
\item Andreas Weinhäusel (Austrian Institute of Technology).
\end{itemize}
\end{frame}


\begin{frame}{Podziękowania}
Współpracownicy:
\begin{itemize}
\item Przemysław Gagat (Uniwersytet Wrocławski).
\item Jarosław Chilimoniuk (Uniwersytet Wrocławski).
\item Rafał Kolenda (Uniwersytet Przyrodniczy we Wrocławiu).
\item Piotr Sobczyk (Politechnika Wrocławska).
\item Sławomir Jabłoński (Uniwersytet Wrocławski).
\item Marlena G\k{a}sior-Głogowska (Politechnika Wrocławska).
\item Chris Lauber (Technical University Dresden).
\item Anna Duda-Madej (Uniwersytet Medyczny im. Piastów Śląskich we Wrocławiu).
\end{itemize}

\end{frame}

\begin{frame}{Podziękowania}
Finansowanie:
\begin{itemize}
\item Narodowe Centrum Nauki (Preludium i Etiuda).
\item COST ACTION CA15110 (Harmonising standardisation strategies to increase efficiency and competitiveness of European life-science research).
\item KNOW Wrocław Center for Biotechnology.
\item InnoProfile-Transfer-Projekt 03IPT611X przyznanym przez Ministerstwo Edukacji i Badań Naukowych Niemiec.
\end{itemize}

\end{frame}

\begin{frame}[allowframebreaks]{Publikacje}

\small
\begin{enumerate}  

\item \underline{Burdukiewicz, M.}, Sobczyk, P., Chilimoniuk, J., Gagat, P., and Mackiewicz, P., \textit{Prediction of Signal Peptides in Proteins from Malaria Parasites}. \textbf{International Journal of Molecular Sciences}, 2018.

\item Kolenda R., \underline{Burdukiewicz M.}, Schiebel J., Rödiger S, Sauer L., Szabo I., Orłowska A., Weinreich J., Nitschke J., Böhm, A., Gerber U., Roggenbuck D., Schierack P., \textit{Adhesion of Salmonella to pancreatic secretory granule membrane major glycoprotein GP2 of human and porcine origin depends on FimH sequence variation}, \textbf{Frontiers in microbiology}, 2018.

\item Mackiewicz D., Posacki P., \underline{Burdukiewicz M.}, Błażej P. \textit{Role of recombination and faithfulness to partner in sex chromosome degeneration}. \textbf{Scientific Reports}, 2018.

\item \underline{Burdukiewicz M.}, Gagat P. Jab\l{}o\'nski S., Chilimoniuk J., 
Gaworski M., Mackiewicz P., \L{}ukaszewicz M. \textit{PhyMet2: a database and toolkit for phylogenetic and metabolic analyses of methanogens}.
\textbf{Environmental Microbiology Reports}, 2018.

\item \underline{Burdukiewicz M.}, Sobczyk P. R\"{o}diger S., Duda-Madej A., 
Mackiewicz P., Kotulska M., \textit{Amyloidogenic motifs revealed by n-gram 
analysis}. 
\textbf{Scientific Reports}, 2017. 

\item Schiebel J., B\"{o}hm A., Nitschke J., \underline{Burdukiewicz M.}, 
Weinreich J., Ali A., Roggenbuck
D., R\"{o}diger S., Schierack P., \textit{Genotypic and phenotypic 
characteristics in association
with biofilm formation in different pathotypes of human clinical Escherichia 
coli isolates},
\textbf{Applied and Environmental Microbiology}, 2017.

\item R\"{o}diger S., \underline{Burdukiewicz M.}, Spiess A.-N., Blagodatskikh 
K., \textit{Enabling reproducible real-time quantitative PCR research: the RDML 
package}. 
\textbf{Bioinformatics}, 2017.

\item \underline{Burdukiewicz M.}, R\"{o}diger S., Sobczyk P., Menschikowski 
M., Schierack P.,
Mackiewicz P., \textit{Methods for comparing multiple digital PCR experiments}, 
\textbf{Biomolecular
Detection and Quantification}, 2016.

\item Spiess A.-N., R\"{o}diger S., \underline{Burdukiewicz M.}, Volksdorf T., 
Tellinghuisen J., \textit{System-
specific periodicity in quantitative real-time polymerase chain reaction data 
questions
threshold-based quantitation}, \textbf{Scientific Reports}, 2016.

\item Kolenda R., \underline{Burdukiewicz M.}, Schierack P., \textit{A 
systematic review and meta-analysis of the epidemiology of pathogenic 
escherichia coli of calves and the role of calves as reservoirs for human 
pathogenic E. coli}. \textbf{Frontiers in Cellular and Infection Microbiology}, 
2015.

\item R\"{o}diger S., \underline{Burdukiewicz M.}, Schierack P., 
\textit{chipPCR: an R Package to Pre-Process Raw Data of Amplification Curves}. 
\textbf{Bioinformatics}, 2015.

\item R\"{o}diger S., \underline{Burdukiewicz M.}, Blagodatskikh K., Jahn M., 
Schierack P., 
\textit{R as an
Environment for the Reproducible Analysis of DNA Amplification Experiments}, 
\textbf{R Journal}, 2015.

\item Spiess A.-N., Deutschmann C., \underline{Burdukiewicz M.}, Himmelreich 
R., 
Klat K., Schierack P., R\"{o}diger S., \textit{Impact of smoothing on parameter 
estimation in quantitative dna amplification experiments}. \textbf{Clinical 
Chemistry}, 2014.

\end{enumerate}
\end{frame}

\begin{frame}{Podsumowanie}
\small\begin{itemize}
\item Zastosowanie n-gramów (k-merów), czyli ciągów aminokwasów lub nukleotydów o długości $n$ okazało się skuteczne do charakterystyki sekwencji peptydów sygnałowych i amyloidogennych oraz markerów molekularnych metanogenów, a następnie do przewidywania tych peptydów oraz optymalnych warunków hodowli metanogenów w oparciu o te markery.
\item Zastosowanie uproszczonych alfabetów aminokwasowych, w których aminokwasy są grupowane ze względu na swoje podobieństwo fizykochemiczne lub funkcjonalne, okazało się bardzo dobrym podejściem do opisu sekwencji aminokwasowych o zróżnicowanym składzie i wyeksponowania ich cech istotnych do przewidywania peptydów sygnałowych i amyloidogennych.
\item Opracowana procedura QuiPT (\textbf{Qui}ck \textbf{P}ermutation \textbf{T}est) pozwala na szybki wybór najbardziej informatywnych n-gramów i uzyskiwanie dokładnych p-wartości.
\item Zastosowana metodologia tworzenia uproszczonych alfabetów umożliwia identyfikowania kluczowych cech związanych z charakterystycznymi cechami peptydów.
\end{itemize}
\end{frame}  


\begin{frame}[allowframebreaks]
        \frametitle{References}
  \bibliographystyle{apalike}
  \bibliography{references}
\end{frame}  


\begin{frame}{Upraszczanie alfabetów i QuiPT - wyjaśnienia}

\begin{itemize}
\item QuiPT został zaprojektowany do zadań typowych w przewidywaniu właściwości sekwencji, gdzie często stosuje się dane binarne.
\item Zwykłe metody upraszczania alfabetów zalecają duże (np. powyżej 1000 białek zawierających ok. 26000 reszt aminokwasowych) zbiory danych. Bacardit, J., Stout, M., Hirst, J.D., Valencia, A., Smith, R.E., and Krasnogor, N. (2009). Automated Alphabet Reduction for Protein Datasets. BMC Bioinformatics 10, 6.
\end{itemize}

\end{frame}



\begin{frame}[allowframebreaks]{signalHsmm - wyjaśnienia}

\begin{itemize}
\item Trudno stworzyć program lepszy dla ogólu peptydów sygnałowych niż signalP 4.1, ponieważ większość z nich jest często najpierw idenyfikowana \textit{in silico} przez signalP 4.1 (komunikacja ustna: H. Nielsen)

\item Nie ma dużego zbioru danych peptydów sygnałowych w białkach \textit{Plasmodium} sp. potwierdzonych eksperymentalnie. Inne narzędzia np. ApicoAP też wykorzystują zbiór danych użyty do walidacji signalHsmm. Właściwości tych potencjalnych peptydów sygnalowych są ewidentne, a same peptydy występują przy białkach ulegających sekrecji.

\end{itemize}

\end{frame}


\begin{frame}[allowframebreaks]{AmyloGram - wyjaśnienia}

Zdefiniowane długości n-gramów pochodzą z prac eksperymentalnych definiujących motywy amyloidogenne:
\begin{itemize}
\item de Groot, N.S., Parella, T., Aviles, F.X., Vendrell, J., and Ventura, S. (2007). \textit{Ile-Phe Dipeptide Self-Assembly: Clues to Amyloid Formation}. Biophysical Journal 92, 1732–1741.
\item Ivanova, M.I., Thompson, M.J., and Eisenberg, D. (2006). \textit{A systematic screen of β2-microglobulin and insulin for amyloid-like segments}. Proc Natl Acad Sci U S A 103, 4079–4082.
\item Sant’Anna, R., Fernández, M.R., Batlle, C., Navarro, S., de Groot, N.S., Serpell, L., and Ventura, S. (2016). Characterization of Amyloid Cores in Prion Domains. Scientific Reports 6, 34274.
\end{itemize}

\end{frame}


\begin{frame}{AmyloGram - wyjaśnienia}
\begin{table}[ht]
\centering

\begin{tabular}{ccccc}
  \toprule
Program & AUC & MCC \\ 
  \midrule
AmyloGram & \textbf{0.8972} & \textbf{0.6307} \\ 
  \rowcolor{white}PASTA 2.0 \citep{walsh_pasta_2014} & 0.8550 & 0.4291  \\ 
   FoldAmyloid \citep{garbuzynskiy_foldamyloid:_2010} & 0.7351 & 0.4526  \\ 
  \rowcolor{white}APPNN \citep{familia_prediction_2015} & 0.8343 & 0.5823  \\ 
   \bottomrule
\end{tabular}
\end{table}

Klasyfikator wytrenowany z wykorzystaniem najlepszego uproszczonego alfabetu, AmyloGram, został porównany z innymi narzędziami do przewidywania amyloidów z użyciem zewnętrznego zbioru danych \textit{pep424}.
\btVFill
\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
\end{frame}

\begin{frame}{MethanoGram - wyjaśnienia}

\begin{itemize}

\item MethanoGram trafnie przewiduje tylko dwa spośród czterech wybranych warunków hodowlanych, ale są to jedne z kluczowych parametrów.

\item Narzędzie jest dedykowane dla wąskich grup mikroorganizmów. Jego zasada działania w oparciu o markery molekularne, utrudnia zastosowanie do szerszych grup.

\end{itemize}

\end{frame}


\begin{frame}[allowframebreaks]{QuiPT - wyjaśnienia}

\begin{enumerate}
    
\item Hipoteza testu: dwustronna.

$H_0$: częstość występowania n-gramu z danej sekwencji nie jest związane z przynależnością tej sekwencji do danej grupy.

$H_A$: częstość występowania n-gramu z danej sekwencji jest związane z przynależnością tej sekwencji do danej grupy.

\item Statystyka testowa: wzajemna informacja $I$ zdefiniowana następującym wzorem:

$\operatorname{I}(X;Y) = \sum_{y \in \mathcal Y} \sum_{x \in \mathcal X}
    { p(x,y) \log{ \left(\frac{p(x,y)}{p(x)\,p(y)} \right) }}$

\begin{itemize}

\item p(x,y): wspólny rozkład prawdopodobieństwa X i Y.

\item p(x): rozkład brzegowy X.

\item X: zmienna losowa o rozkładzie dwumianowym (obecność n-gramu w sekwencji).

\item Y: zmienna losowa o rozkładzie dwumianowym (przynależność sekwencji do grupy).

\end{itemize}

\item Moc testu opartego na wzajemnej informacji:

\begin{itemize}

\item François, D., Wertz, V., and Verleysen, M. (2006). \textit{The permutation test for feature selection by mutual information}. Proceedings of the 14th European Symposium on Artificial Neural Networks (ESANN 2006).

\item Szymczak, S., Nuzzo, A., Fuchsberger, C., Schwarz, D.F., Ziegler, A., Bellazzi, R., and Igl, B.-W. (2007). \textit{Genetic association studies for gene expressions: permutation-based mutual information in a comparison with standard ANOVA and as a novel approach for feature selection}. BMC Proc 1, S9.

\item Airola, A., Pahikkala, T., Boberg, J., and Salakoski, T. (2010). \textit{Applying Permutation Tests for Assessing the Statistical Significance of Wrapper Based Feature Selection}. In 2010 Ninth International Conference on Machine Learning and Applications, pp. 989–994.


\end{itemize}


\item Test został nazwany permutacyjnym, ponieważ zastępuje testy permutacyjne niezależności rozkładów. W literaturze przedmiotu testy te zwyczajowo nazywane są permutacyjnymi, dlatego przyjęto nazwę w konwencji stosowanej przez typowych użytkowników. Dzięki tej nazwie test będzie lepiej rozpoznawany przez potencjalnych użytkowników.

\item Stosuje się test dwustronny, ponieważ zarówno elementy nadreprezentowane jak i niedoreprezentowane ponieważ te ostatnie wnoszą cenną informację o układach, które są zabronione w danym układzie.

\item p-wartości: dowolnie małe w zależności od zbioru danych.

\end{enumerate}

\end{frame}

\begin{frame}[allowframebreaks]{Upraszczanie alfabetów - wyjaśnienia}

\begin{itemize}
\item Grupowanie aminokwasów: odleglość euklidesowa, normalizacja 0-1.

\item Uzyskanie reprezentacji alfabetu aminokwasowego dla małej liczby sekwencji nie jest możliwe za pomocą metod głębokich.
\end{itemize}

\end{frame}


\begin{frame}[allowframebreaks]{signalHsmm - wyjaśnienia}

\begin{itemize}
\item W literaturze predmiotu preferowane są modele o największej czułości (Petersen, T.N., Brunak, S., von Heijne, G., and Nielsen, H. (2011). SignalP 4.0: Discriminating Signal Peptides from Transmembrane Regions. Nature Methods 8, 785). Wybrany alfabet zapewnia zarówno największą czułość jak i AUC.

\item Odchylenia standardowe uzyskanych alfabetów zostały obliczone w drodze 10-krotnej walidacji krzyżowej. Ich niewielka zmienność wynika z dużej stabilności uzyskanego klasyfikatora, którą można zaobserwować porównując iterację uczoną na danych z 1987 roku i 2010 roku.
 
\item Wnioski na stronie 40 wynikają z wielu tabel i rysunków, przykładowo rys. 9.

\item PCA: przedstawone na rysunku dwa pierwsze komponenty składowe wyjaśniają 40\% wariancji.

\end{itemize}

\end{frame}

\begin{frame}{AmyloGram - wyjaśnienia}

<<echo = FALSE,message=FALSE,fig.align='center',fig.height=4,warning=FALSE>>=
select(ngram_freq_plot, -association) %>% 
  dcast(decoded_name ~ variable) %>% 
  mutate(log_odd = log(Amyloid/Nieamyloid)) %>% 
  ggplot(aes(x = decoded_name, y = log_odd)) +
  geom_col() +
  scale_y_continuous("Log odds ration") +
  scale_x_discrete("") +
  theme_bw(base_size = 18) +
  theme(panel.grid.major.y = element_line(color = "lightgrey", size = 0.5),
        legend.position = "bottom") 
@

\end{frame}


\begin{frame}{MethanoGram - wyjaśnienia}

Mały zbiór danych (61 gatunków) nie pozwala na tworzenie modelu uwzględniającego zbyt wiele cech.

\end{frame}

\begin{frame}{Podobieństwo alfabetów i jakość predykcji}
Czy alfabety podobne do najlepszego uproszczonego alfabetu również dobrze przewidują amyloidy?
\end{frame}

\begin{frame}{Similarity index}
<<echo = FALSE,message=FALSE,fig.align='center',fig.height=4,warning=FALSE>>=
si_dat <- read.csv2("si_dat.csv")

levels(si_dat[["et"]]) <- c("Najlepszy uproszczony alfabet", "Uproszczony alfabet", 
                             "Pełny alfabet", "Standardowy uproszczony alfabet", 
                            "Standardowy uproszczony alfabet")


simil_plot <- ggplot(si_dat, aes(x=si, y=AUC_mean)) + 
  # geom_point(data = si_dat, 
  #            aes(x = si, y = AUC_mean, color = et, shape = et), size = 4) +
  #geom_density_2d(color = "black", contour = TRUE) +
    geom_bin2d(bins = 30) +
  # stat_density2d(aes(fill=..level..), color = "black",
  #                contour = TRUE, geom = "polygon", alpha = 0.5, binwidth = 50, bins = 10) +
  scale_fill_continuous("Liczba alfabetów", low = "gold", high = "goldenrod4") +
  xlab("Similarity index") +
  ylab("AUC") +
  my_theme +
  geom_point(data = droplevels(filter(si_dat, et != "Uproszczony alfabet")),
             aes(x = si, y = AUC_mean, color = et, shape = et), size = 4) +
  guides(color = guide_legend(nrow = 2), shape = guide_legend(nrow = 2), 
         fill = guide_colorbar(barwidth = unit(5, "line"))) +
  scale_shape_manual("", values = c(16, 15, 15), drop = FALSE) +
  scale_color_manual("", values = c("red", "green", "blue"), drop = FALSE) +
  theme(panel.grid.major = element_line(color = "lightgrey", size = 0.5)) 

print(simil_plot)
@
Similarity index~\citep{stephenson_unearthing_2013} mierzy podobieństwo między dwoma uproszczonymi alfabetami (1:~identyczne alfabety, 0:~zupełnie niepodobne alfabety).

\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
\end{frame}



\begin{frame}{Similarity index}
<<echo = FALSE,message=FALSE,fig.align='center',fig.height=4,warning=FALSE>>=
print(simil_plot)
@
Korelacja między similarity index i średnim AUC jest istotna ($\textrm{p-value} \leq 2.2^{-16}$; $\rho = 0.51$).
\tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
\end{frame}
\end{document}